/* Generated by the Apache Thrift C11 compiler. */
#include "calculator_types.h"
#include <stdlib.h>
#include <string.h>

enum thrift_status example_calculation_error_create(struct example_calculation_error **out, size_t *budget)
{
    void *allocation = NULL;
    enum thrift_status status;
    if (!out) return THRIFT_NULL_VALUE;
    if (*out) return THRIFT_OUTPUT_NOT_EMPTY;
    status = thrift_alloc(1, sizeof(struct example_calculation_error), budget, &allocation);
    if (status != THRIFT_OK) return status;
    status = thrift_record_init_limited(&example_calculation_error_record, allocation, budget);
    if (status != THRIFT_OK) {
        free(allocation);
        return status;
    }
    *out = allocation;
    return THRIFT_OK;
}

struct example_calculation_error *example_calculation_error_new(void)
{
    struct example_calculation_error *value = NULL;
    if (example_calculation_error_create(&value, NULL) != THRIFT_OK) return NULL;
    return value;
}

enum thrift_status example_calculation_error_set_message(struct example_calculation_error *value, const void *data, size_t size)
{
    enum thrift_status status;
    if (!value) return THRIFT_NULL_VALUE;
    if (!data && size) return THRIFT_NULL_DATA;
    status = thrift_bytes_set(&value->f_message, data, size);
    if (status != THRIFT_OK) return status;
    value->has_message = true;
    return THRIFT_OK;
}

static const struct thrift_field example_calculation_error_fields[] = {
    {1, offsetof(struct example_calculation_error, f_message), offsetof(struct example_calculation_error, has_message), true, false, &thrift_type_string},
};
const struct thrift_record example_calculation_error_record = {
    sizeof(struct example_calculation_error), 1, example_calculation_error_fields, false, NULL
};
const struct thrift_type example_calculation_error_type_descriptor = {
    THRIFT_STRUCT, sizeof(struct example_calculation_error *), &example_calculation_error_record, NULL, NULL
};

enum thrift_status example_calculation_error_init(struct example_calculation_error *value)
{
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_init(&example_calculation_error_record, value);
}
void example_calculation_error_clear(struct example_calculation_error *value)
{
    thrift_record_clear(&example_calculation_error_record, value);
}
enum thrift_status example_calculation_error_read(struct thrift_protocol *protocol, struct example_calculation_error *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_read(protocol, &example_calculation_error_record, value);
}
enum thrift_status example_calculation_error_write(struct thrift_protocol *protocol, const struct example_calculation_error *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_write(protocol, &example_calculation_error_record, value);
}

enum thrift_status example_calculator_add_args_create(struct example_calculator_add_args **out, size_t *budget)
{
    void *allocation = NULL;
    enum thrift_status status;
    if (!out) return THRIFT_NULL_VALUE;
    if (*out) return THRIFT_OUTPUT_NOT_EMPTY;
    status = thrift_alloc(1, sizeof(struct example_calculator_add_args), budget, &allocation);
    if (status != THRIFT_OK) return status;
    status = thrift_record_init_limited(&example_calculator_add_args_record, allocation, budget);
    if (status != THRIFT_OK) {
        free(allocation);
        return status;
    }
    *out = allocation;
    return THRIFT_OK;
}

struct example_calculator_add_args *example_calculator_add_args_new(void)
{
    struct example_calculator_add_args *value = NULL;
    if (example_calculator_add_args_create(&value, NULL) != THRIFT_OK) return NULL;
    return value;
}

static const struct thrift_field example_calculator_add_args_fields[] = {
    {1, offsetof(struct example_calculator_add_args, f_left), offsetof(struct example_calculator_add_args, has_left), true, false, &thrift_type_i64},
    {2, offsetof(struct example_calculator_add_args, f_right), offsetof(struct example_calculator_add_args, has_right), true, false, &thrift_type_i64},
};
const struct thrift_record example_calculator_add_args_record = {
    sizeof(struct example_calculator_add_args), 2, example_calculator_add_args_fields, false, NULL
};
const struct thrift_type example_calculator_add_args_type_descriptor = {
    THRIFT_STRUCT, sizeof(struct example_calculator_add_args *), &example_calculator_add_args_record, NULL, NULL
};

enum thrift_status example_calculator_add_args_init(struct example_calculator_add_args *value)
{
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_init(&example_calculator_add_args_record, value);
}
void example_calculator_add_args_clear(struct example_calculator_add_args *value)
{
    thrift_record_clear(&example_calculator_add_args_record, value);
}
enum thrift_status example_calculator_add_args_read(struct thrift_protocol *protocol, struct example_calculator_add_args *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_read(protocol, &example_calculator_add_args_record, value);
}
enum thrift_status example_calculator_add_args_write(struct thrift_protocol *protocol, const struct example_calculator_add_args *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_write(protocol, &example_calculator_add_args_record, value);
}

enum thrift_status example_calculator_add_result_create(struct example_calculator_add_result **out, size_t *budget)
{
    void *allocation = NULL;
    enum thrift_status status;
    if (!out) return THRIFT_NULL_VALUE;
    if (*out) return THRIFT_OUTPUT_NOT_EMPTY;
    status = thrift_alloc(1, sizeof(struct example_calculator_add_result), budget, &allocation);
    if (status != THRIFT_OK) return status;
    status = thrift_record_init_limited(&example_calculator_add_result_record, allocation, budget);
    if (status != THRIFT_OK) {
        free(allocation);
        return status;
    }
    *out = allocation;
    return THRIFT_OK;
}

struct example_calculator_add_result *example_calculator_add_result_new(void)
{
    struct example_calculator_add_result *value = NULL;
    if (example_calculator_add_result_create(&value, NULL) != THRIFT_OK) return NULL;
    return value;
}

enum example_calculator_add_result_case example_calculator_add_result_case(const struct example_calculator_add_result *value)
{
    enum example_calculator_add_result_case selected = EXAMPLE_CALCULATOR_ADD_RESULT_CASE_NONE;
    if (!value) return EXAMPLE_CALCULATOR_ADD_RESULT_CASE_INVALID;
    if (value->has_success) {
        if (selected != EXAMPLE_CALCULATOR_ADD_RESULT_CASE_NONE) return EXAMPLE_CALCULATOR_ADD_RESULT_CASE_INVALID;
        selected = EXAMPLE_CALCULATOR_ADD_RESULT_CASE_FIELD_SUCCESS;
    }
    if (value->has_error) {
        if (selected != EXAMPLE_CALCULATOR_ADD_RESULT_CASE_NONE) return EXAMPLE_CALCULATOR_ADD_RESULT_CASE_INVALID;
        selected = EXAMPLE_CALCULATOR_ADD_RESULT_CASE_FIELD_ERROR;
    }
    return selected;
}

enum thrift_status example_calculator_add_result_set_success(struct example_calculator_add_result *value, int64_t field)
{
    if (!value) return THRIFT_NULL_VALUE;
    example_calculator_add_result_clear(value);
    value->f_success = field;
    value->has_success = true;
    return THRIFT_OK;
}

enum thrift_status example_calculator_add_result_set_error(struct example_calculator_add_result *value, struct example_calculation_error * field)
{
    if (!value) return THRIFT_NULL_VALUE;
    if (!field) return THRIFT_NULL_FIELD;
    if ((const void *)field == (const void *)value) return THRIFT_INVALID_OWNERSHIP;
    if (value->f_error == field) value->f_error = NULL;
    example_calculator_add_result_clear(value);
    value->f_error = field;
    value->has_error = true;
    return THRIFT_OK;
}

static const struct thrift_field example_calculator_add_result_fields[] = {
    {0, offsetof(struct example_calculator_add_result, f_success), offsetof(struct example_calculator_add_result, has_success), false, true, &thrift_type_i64},
    {1, offsetof(struct example_calculator_add_result, f_error), offsetof(struct example_calculator_add_result, has_error), false, true, &example_calculation_error_type_descriptor},
};
const struct thrift_record example_calculator_add_result_record = {
    sizeof(struct example_calculator_add_result), 2, example_calculator_add_result_fields, true, NULL
};
const struct thrift_type example_calculator_add_result_type_descriptor = {
    THRIFT_STRUCT, sizeof(struct example_calculator_add_result *), &example_calculator_add_result_record, NULL, NULL
};

enum thrift_status example_calculator_add_result_init(struct example_calculator_add_result *value)
{
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_init(&example_calculator_add_result_record, value);
}
void example_calculator_add_result_clear(struct example_calculator_add_result *value)
{
    thrift_record_clear(&example_calculator_add_result_record, value);
}
enum thrift_status example_calculator_add_result_read(struct thrift_protocol *protocol, struct example_calculator_add_result *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_read(protocol, &example_calculator_add_result_record, value);
}
enum thrift_status example_calculator_add_result_write(struct thrift_protocol *protocol, const struct example_calculator_add_result *value)
{
    if (!protocol) return THRIFT_NULL_PROTOCOL;
    if (!protocol->ops) return THRIFT_PROTOCOL_UNINITIALIZED;
    if (!value) return THRIFT_NULL_VALUE;
    return thrift_record_write(protocol, &example_calculator_add_result_record, value);
}

static enum thrift_status example_calculator_add_invoke(void *handler_context, const void *args, void *result)
{
    struct example_calculator_handler *handler = handler_context;
    if (!handler) return THRIFT_NULL_HANDLER;
    if (!args) return THRIFT_NULL_ARGS;
    if (!result) return THRIFT_NULL_RESULT;
    if (!handler->f_add) return THRIFT_MISSING_CALLBACK;
    return handler->f_add(handler->user_context, args, result);
}

static const struct thrift_method example_calculator_methods[] = {
    {"\141\144\144", &example_calculator_add_args_record, &example_calculator_add_result_record, false, true, example_calculator_add_invoke},
};

enum thrift_status example_calculator_add_call(struct thrift_protocol *protocol, int32_t sequence,
    const struct example_calculator_add_args *args, struct example_calculator_add_result *result)
{
    return thrift_client_call(protocol, &example_calculator_methods[0], sequence, args, result);
}

struct thrift_service example_calculator_service(struct example_calculator_handler *handler)
{
    struct thrift_service service = {"\103\141\154\143\165\154\141\164\157\162", example_calculator_methods, 1, handler};
    return service;
}

enum thrift_status example_calculator_process(struct thrift_protocol *protocol,
    struct example_calculator_handler *handler)
{
    return thrift_process(protocol, example_calculator_methods, 1, handler);
}

