/* Generated by the Apache Thrift C11 compiler. */
#ifndef CALCULATOR_TYPES_H
#define CALCULATOR_TYPES_H

#include <thrift/c11/processor/thrift_processor.h>

/**
 * @file
 */
struct example_calculation_error;

struct example_calculation_error {
    struct thrift_bytes f_message;
    bool has_message;
};
extern const struct thrift_record example_calculation_error_record;
extern const struct thrift_type example_calculation_error_type_descriptor;
enum thrift_status example_calculation_error_init(struct example_calculation_error *value);
void example_calculation_error_clear(struct example_calculation_error *value);
enum thrift_status example_calculation_error_read(struct thrift_protocol *protocol, struct example_calculation_error *value);
enum thrift_status example_calculation_error_write(struct thrift_protocol *protocol, const struct example_calculation_error *value);

/**
 * Allocate and initialize an owned record, charging all allocations to the optional budget.
 * out must point to NULL; failure preserves it, but consumed budget is not refunded.
 * Returns THRIFT_NULL_VALUE, THRIFT_OUTPUT_NOT_EMPTY, THRIFT_LIMIT or THRIFT_NOMEM on failure.
 * Release with _clear() followed by free().
 */
enum thrift_status example_calculation_error_create(struct example_calculation_error **out, size_t *budget);
/**
 * Allocate with defaults; returns NULL on failure. Use _create() for an exact status/budget.
 * Release with _clear() followed by free().
 */
struct example_calculation_error *example_calculation_error_new(void);
/**
 * Assign the field and mark it present. THRIFT_NULL_VALUE denotes a NULL destination.
 * Copies size bytes; nonempty NULL input returns THRIFT_NULL_DATA. May return THRIFT_LIMIT or THRIFT_NOMEM.
 * Failure preserves the record; source bytes may overlap its owned storage.
 */
enum thrift_status example_calculation_error_set_message(struct example_calculation_error *value, const void *data, size_t size);
struct example_calculator_add_args {
    int64_t f_left;
    bool has_left;
    int64_t f_right;
    bool has_right;
};
extern const struct thrift_record example_calculator_add_args_record;
extern const struct thrift_type example_calculator_add_args_type_descriptor;
enum thrift_status example_calculator_add_args_init(struct example_calculator_add_args *value);
void example_calculator_add_args_clear(struct example_calculator_add_args *value);
enum thrift_status example_calculator_add_args_read(struct thrift_protocol *protocol, struct example_calculator_add_args *value);
enum thrift_status example_calculator_add_args_write(struct thrift_protocol *protocol, const struct example_calculator_add_args *value);

/**
 * Allocate and initialize an owned record, charging all allocations to the optional budget.
 * out must point to NULL; failure preserves it, but consumed budget is not refunded.
 * Returns THRIFT_NULL_VALUE, THRIFT_OUTPUT_NOT_EMPTY, THRIFT_LIMIT or THRIFT_NOMEM on failure.
 * Release with _clear() followed by free().
 */
enum thrift_status example_calculator_add_args_create(struct example_calculator_add_args **out, size_t *budget);
/**
 * Allocate with defaults; returns NULL on failure. Use _create() for an exact status/budget.
 * Release with _clear() followed by free().
 */
struct example_calculator_add_args *example_calculator_add_args_new(void);
/**
 * Assign the field and mark it present. THRIFT_NULL_VALUE denotes a NULL destination.
 */
static inline enum thrift_status example_calculator_add_args_set_left(struct example_calculator_add_args *value, int64_t field)
{
    if (!value) return THRIFT_NULL_VALUE;
    value->f_left = field;
    value->has_left = true;
    return THRIFT_OK;
}

/**
 * Assign the field and mark it present. THRIFT_NULL_VALUE denotes a NULL destination.
 */
static inline enum thrift_status example_calculator_add_args_set_right(struct example_calculator_add_args *value, int64_t field)
{
    if (!value) return THRIFT_NULL_VALUE;
    value->f_right = field;
    value->has_right = true;
    return THRIFT_OK;
}

struct example_calculator_add_result {
    int64_t f_success;
    bool has_success;
    struct example_calculation_error * f_error;
    bool has_error;
};
extern const struct thrift_record example_calculator_add_result_record;
extern const struct thrift_type example_calculator_add_result_type_descriptor;
enum thrift_status example_calculator_add_result_init(struct example_calculator_add_result *value);
void example_calculator_add_result_clear(struct example_calculator_add_result *value);
enum thrift_status example_calculator_add_result_read(struct thrift_protocol *protocol, struct example_calculator_add_result *value);
enum thrift_status example_calculator_add_result_write(struct thrift_protocol *protocol, const struct example_calculator_add_result *value);

/**
 * Allocate and initialize an owned record, charging all allocations to the optional budget.
 * out must point to NULL; failure preserves it, but consumed budget is not refunded.
 * Returns THRIFT_NULL_VALUE, THRIFT_OUTPUT_NOT_EMPTY, THRIFT_LIMIT or THRIFT_NOMEM on failure.
 * Release with _clear() followed by free().
 */
enum thrift_status example_calculator_add_result_create(struct example_calculator_add_result **out, size_t *budget);
/**
 * Allocate with defaults; returns NULL on failure. Use _create() for an exact status/budget.
 * Release with _clear() followed by free().
 */
struct example_calculator_add_result *example_calculator_add_result_new(void);
/**
 * Active alternative. INVALID denotes NULL or multiple manually activated fields.
 */
enum example_calculator_add_result_case {
    EXAMPLE_CALCULATOR_ADD_RESULT_CASE_INVALID = -1,
    EXAMPLE_CALCULATOR_ADD_RESULT_CASE_NONE = 0,
    EXAMPLE_CALCULATOR_ADD_RESULT_CASE_FIELD_SUCCESS = 1,
    EXAMPLE_CALCULATOR_ADD_RESULT_CASE_FIELD_ERROR = 2
};
/**
 * Return the active alternative without allocating or modifying the record.
 */
enum example_calculator_add_result_case example_calculator_add_result_case(const struct example_calculator_add_result *value);
/**
 * Assign the field and mark it present. THRIFT_NULL_VALUE denotes a NULL destination.
 * On success clears every other alternative without reapplying defaults.
 */
enum thrift_status example_calculator_add_result_set_success(struct example_calculator_add_result *value, int64_t field);
/**
 * Assign the field and mark it present. THRIFT_NULL_VALUE denotes a NULL destination.
 * Takes ownership of an unshared, free()-compatible pointer on success. NULL returns THRIFT_NULL_FIELD.
 * Direct self-ownership returns THRIFT_INVALID_OWNERSHIP; releases the previous value on success.
 * Reassigning the same pointer is safe. Descendant aliases are not allowed.
 * On success clears every other alternative without reapplying defaults.
 */
enum thrift_status example_calculator_add_result_set_error(struct example_calculator_add_result *value, struct example_calculation_error * field);
struct example_calculator_handler {
    void *user_context; /**< Borrowed application data passed to method callbacks. */
    enum thrift_status (*f_add)(void *user_context, const struct example_calculator_add_args *args, struct example_calculator_add_result *result);
};
enum thrift_status example_calculator_add_call(struct thrift_protocol *protocol, int32_t sequence,
    const struct example_calculator_add_args *args, struct example_calculator_add_result *result);
struct thrift_service example_calculator_service(struct example_calculator_handler *handler);
enum thrift_status example_calculator_process(struct thrift_protocol *protocol,
    struct example_calculator_handler *handler);

#endif
